name: Testing

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint-and-unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.4'

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/package-operator
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.0 && golangci-lint run ./... --deadline=15m

    - name: Unit
      run: CGO_ENABLED=1 go test -coverprofile=cov.out -race -test.v ./... | tee out.txt

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./cov.out
        token: ${{ secrets.CODECOV_TOKEN }}
